### PR TITLE
Updated player for setting audio and video tracks

### PR DESCRIPTION
**Pull request by sreeise**
This pull request is for being able to set video and audio tracks and is part of Servo issue [22799](https://github.com/servo/servo/issues/22799). 

Servo should be able to set multiple audio tracks at one time but the work here only allows for one. If anyone has any advice on how to set multiple audio tracks that would be great!

### CODE REVIEW

**Comment by ferjm** [comment]
There's previous work done to play multiple audio tracks simultaneously with `audiomixer`.

https://mozilla.logbot.info/servo-media/20190911#c16606524-c16606984

**Comment by sreeise** [comment]
> There's previous work done to play multiple audio tracks simultaneously with `audiomixer`.
> 
> https://mozilla.logbot.info/servo-media/20190911#c16606524-c16606984

Ahh interesting. I am not too familiar with how the GStreamer plugins are done in servo media and I am assuming audiomixer is a plugin here. Could you point me in the general direction of where this is done or how it could be done in servo media if you don't mind?

**Comment by jdm** [comment]
https://coaxion.net/blog/2013/11/synchronized-audio-mixing-in-gstreamer/ has a little bit of information about the audiomixer plugin and how it can fit into a gstreamer audio pipeline.

**Pull request merged**
