### PR TITLE
chore(deps): bump `smallvec` from `^0.6` to `^1`

### PR DESCRIPTION
**Pull request by yvt**
Part of <https://github.com/servo/servo/issues/24830>

### CODE REVIEW

**Comment by yvt** [comment]
https://ci.appveyor.com/project/jdm/media/builds/45027983#L412

```
error: field `buffer` is never read
  --> player\video.rs:19:5
   |
15 | pub struct VideoFrame {
   |            ---------- field in this struct
...
19 |     buffer: Arc<dyn Buffer>,
   |     ^^^^^^
   |
   = note: `VideoFrame` has a derived impl for the trait `Clone`, but this is intentionally ignored during dead code analysis
   = note: `-D dead-code` implied by `-D warnings`
```

**Comment by yvt** [comment]
Opened #387 to address the lint errors.

**Comment by jdm** [comment]
@bors-servo r+
Thanks!

**Comment by jdm** [comment]
Ooh, we need to migrate from travisci/appveyor to github actions in this repo.

**Comment by jdm** [comment]
https://github.com/servo/media/pull/388

**Pull request merged**
