### PR TITLE
Render android

### PR DESCRIPTION
**Pull request by ceyusa**
Add GL render for android target, which is a unix type with only EGL.

### CODE REVIEW

**Comment by ceyusa** [comment]
removed the GL context activation

**Comment by ceyusa** [comment]
Can we merge this for now? @ferjm, @asajeffrey ?

**Comment by ferjm** [comment]
Yes, I think we can merge as soon as CI is happy.

**Comment by asajeffrey** [comment]
Fine by me. it would be nice if we could figure out a way to use features rather than gating on `target_os`, to reduce the amount of code duplication, but that's an orthogonal issue.

**Pull request merged**
