### PR TITLE
Queue a/v data while player is setting up

### PR DESCRIPTION
**Pull request by ferjm**
r? @jdm

### CODE REVIEW

**Comment by philn** [comment]
appsrc uses a queue internally, why not increase its size?

**Comment by ferjm** [comment]
That's a great question :D. I'll revert and use appsrc's internal queue. Thanks!

**Comment by ferjm** [comment]
Actually, we can handle this in a different way. We can make the player signal when it's ready and do not start any resource request until we get that signal, this way we won't need to queue any data.

**Pull request merged**
