### PR TITLE
ulong is u32, not u64

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by sdroege** [comment]
Where does the `ulong` come from exactly? If there's really a C `unsigned long` / `gulong` somewhere here then this change is wrong. `unsigned long` is 64 bit on all 64 bit architectures except for Windows.

**Comment by sdroege** [comment]
Use `libc::c_ulong` if you need the correct type, btw

**Comment by Manishearth** [comment]
Oh, this is JavaScript ulong, which is u32

**Comment by sdroege** [comment]
Oh how confusing. Nevermind then :)

**Pull request merged**
