### PR TITLE
Shutdown audio contexts and players in all the examples

### PR DESCRIPTION
**Pull request by ferjm**

### CODE REVIEW

**Comment by ceyusa** [comment]
lgtm

@bors-servo r+

**Comment by jdm** [comment]
Out of curiosity, what is the current behaviour without these changes?

**Comment by ceyusa** [comment]
> Out of curiosity, what is the current behaviour without these changes?

AFAIK the media elements in the examples are not removed from the global hashmaps.

**Comment by Manishearth** [comment]
Why not have a destructor on the context handle that sends a shutdown message on death?

**Comment by ferjm** [comment]
> > Out of curiosity, what is the current behaviour without these changes?
> 
> AFAIK the media elements in the examples are not removed from the global hashmaps.

Essentially that. Although these are weak references to the media elements. And they may be removed on following mutes/unmutes.

> Why not have a destructor on the context handle that sends a shutdown message on death?

Could you elaborate on this, please? We can improve this by making the Player/AudioContext send such a message to the owner GStreamerBackend on drop. I am not sure if that's what you meant.

**Comment by ceyusa** [comment]
Just to clarify, the Backend, once instantiated, it is kept alive until the browser shutdowns, then we should remove the media elements when they are removed of the webpage while the browser keeps running.

**Comment by ceyusa** [comment]
bors-servo ignores me :(

Well, perhaps it is better to clarify these questions before merging :)

**Comment by ferjm** [comment]
Closing in favor of #279

**Pull request closed without merging**
