### PR TITLE
Update to uuid 0.8

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
Pretty sure that's unrelated to my change, what's going on?

**Comment by Manishearth** [comment]
looks like a cargo feature change

cc @ferjm

**Comment by nox** [comment]
Thanks Manish.

As for the Cargo change, I [found](https://github.com/rust-lang/cargo/commit/bf474ba58962261ba992c298cee2dd7352b8b3fe) it.

**Pull request merged**
