### PR TITLE
Bump euclid to 0.22 and update version

### PR DESCRIPTION
**Pull request by mrobinson**

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
I had to do https://github.com/servo/unicode-bidi/pull/93 to fix appveyor but we should probably consider just using GHA's builtin Windows support

**Comment by mrobinson** [comment]
> I had to do [servo/unicode-bidi#93](https://github.com/servo/unicode-bidi/pull/93) to fix appveyor but we should probably consider just using GHA's builtin Windows support

:worried: Looks like the failure uncovered a bit of a mess with the examples. I've had to hold back the version of euclid for the examples to get things working here.

**Pull request merged**
